### ISSUE TITLE
WebActions backend

### ISSUE THREAD

**Issue by martastain** [ynput/ayon-backend#182]
## Story

An addon may expose an action that a user can run on a selection of entities from the web interface.

## TODO

- [ ] Mechanism allowing addons to expose available actions
- [ ] REST endpoint to get list of available actions for the given context
- [ ] REST endpoint to run the action
- [ ] Utilize the event system to keep track of requested/running actions
