### ISSUE TITLE
User inbox resolver

### ISSUE THREAD

**Issue by martastain** [ynput/ayon-backend#189]
## Story

A user wants to see a list of all relevant activities across all projects.

### Problems

Activities are currently accessible only by selecting an entity.

### Proposal

Create a SQL function returning activity_feed.* for all activities referencing the given user across all projects (or all active projects user has access to). Proof of concept for this is ready and working

GraphQL resolver with the following arguments:

### `showActiveProjects: bool | None = None`

- When set to `true`, activities from active projects
- When set to `false` activities from inactive projects will be returned
- When set to `null` activities from all projects will be returned

### `showActiveMessages: bool | None = True`

- When set to `true` (default) only activity references marked as active will be returned. This is an equivalent of "not done" or "not removed/archived".
- When set to `false` only archived/done messages will be returned (a.k.a. trash)
- When set to `null` both done and not done will be reurned

### `showUnreadMessages: bool | None = None`

- The same, but for the `read` flag

`active` and `read` flags can be set using `[POST] /api/inbox` endpoint. Using that endpoint a list of reference_ids can be set to `unread`,  `read` or `inactive`. Inactive implies `read`.

## TODO

- [x] Postgres backend (get_user_inbox function)
- [x] GraphQL resolver for inbox items (reusing ActivityNode)
- [x] Endpoints to manage read/subscription status
- [ ] Notification collector

**Comment by Innders** [comment]
Will there be a difference between "read" and "done"?

Both GitHub and clickup have this difference. 

Done: moves item into a "done" list
Read: stays in the inbox list but is greyed out

**Comment by martastain** [comment]
maybe `active` is closer to `!done` then. and we could store the `read` flag in `referenceData`.

Also, deleting the reference should be completely fine if you wish to eliminate it from `done`. it would disappear from your inbox and when the original activity is updated, it would be re-created.
