### ISSUE TITLE
REST API: Unify SiteID specifications

### ISSUE THREAD

**Issue by martastain** [ynput/ayon-backend#198]
## Story

some endpoints at the moment expect SiteID to be provided as `x-ayon-site-id` header (in `/api/resolve`), others use `?site=` query argument (settings-related endpoints) and some `?site_id=` (project roots) 

### Problems

The current state is messy, different endpoints duplicate the same type hints (or implement that dependency differently)

### Proposal

- `ayon_server.api.dependencies.SiteID` - a dependency used by administration endpoints (such as settings editor), that would return site id specified in query parameter. We need QP here, to create requests from the frontend easily

![image](https://github.com/ynput/ayon-backend/assets/5007200/3ca96107-72ac-4464-915e-70f1b8d26623)

- `ayon_server.api.dependencies.ClientSiteID` - a dependency that takes the site id from the request header, but as a fallback use the site/site_id query param. This will be used for endpoint used by the client. 

![image](https://github.com/ynput/ayon-backend/assets/5007200/d7b45800-2400-4b06-8d45-1eb7cc72cc8b)

This solution also gives us an opportunity to have a single point where to handle SiteID validation.

No addon use SiteID dependency directly in any endpoint, so it is safe to use. Header variant is broken for a while (due to a FastAPI change) so this actually brings back the option to use x-ayon-site-id header for /api/resolve requests ( discovered by @Lyon-Rosenblatt-Ynput ).

## TODO

- [x] Reimplement SiteID and ClientSiteID dependency
- [x] Ensure correct dependencies are used everywhere in the API
- [x] Implement validation
- [x] Endpoints for which site id is mandatory need to assert it is not None
