### ISSUE TITLE
Activities: Watchers

### ISSUE THREAD

**Issue by martastain** [ynput/ayon-backend#298]
## Story

:eyes: 

### Problems

:roll_eyes: 

### Proposal

Implement `watch` activity type. 

## TODO
- [x] Implement GET and POST endpoints for `/api/projects/{projectName}/{entityType}s/{entityId}/watchers`
- [ ] when any supported activity is created, get a list of watchers and add them as additional reference
- [ ] When a user creates their own comment or reviewable on an entity, add them as the watcher
